// A Bison parser, made by GNU Bison 3.2.

// Skeleton interface for Bison LALR(1) parsers in C++

// Copyright (C) 2002-2015, 2018 Free Software Foundation, Inc.

// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

// As a special exception, you may create a larger work that contains
// part or all of the Bison parser skeleton and distribute that work
// under terms of your choice, so long as that work isn't itself a
// parser generator using the skeleton or a modified version thereof
// as a parser skeleton.  Alternatively, if you modify or redistribute
// the parser skeleton itself, you may (at your option) remove this
// special exception, which will cause the skeleton and the resulting
// Bison output files to be licensed under the GNU General Public
// License without this special exception.

// This special exception was added by the Free Software Foundation in
// version 2.2 of Bison.


/**
 ** \file parser.hpp
 ** Define the yy::parser class.
 */

// C++ LALR(1) parser skeleton written by Akim Demaille.

// Undocumented macros, especially those whose name start with YY_,
// are private implementation details.  Do not rely on them.

#ifndef YY_YY_PARSER_HPP_INCLUDED
# define YY_YY_PARSER_HPP_INCLUDED
// //                    "%code requires" blocks.
#line 11 "parserspec.yxx" // lalr1.cc:403

    namespace yy {
        class Lexer;  // Generated by reflex with namespace=yy lexer=Lexer lex=yylex
    }

#line 54 "parser.hpp" // lalr1.cc:403


# include <cstdlib> // std::abort
# include <iostream>
# include <stdexcept>
# include <string>
# include <vector>

// Support move semantics when possible.
#if defined __cplusplus && 201103L <= __cplusplus
# define YY_MOVE           std::move
# define YY_MOVE_OR_COPY   move
# define YY_MOVE_REF(Type) Type&&
# define YY_RVREF(Type)    Type&&
# define YY_COPY(Type)     Type
#else
# define YY_MOVE
# define YY_MOVE_OR_COPY   copy
# define YY_MOVE_REF(Type) Type&
# define YY_RVREF(Type)    const Type&
# define YY_COPY(Type)     const Type&
#endif


#ifndef YYASSERT
# include <cassert>
# define YYASSERT assert
#endif


#ifndef YY_ATTRIBUTE
# if (defined __GNUC__                                               \
      && (2 < __GNUC__ || (__GNUC__ == 2 && 96 <= __GNUC_MINOR__)))  \
     || defined __SUNPRO_C && 0x5110 <= __SUNPRO_C
#  define YY_ATTRIBUTE(Spec) __attribute__(Spec)
# else
#  define YY_ATTRIBUTE(Spec) /* empty */
# endif
#endif

#ifndef YY_ATTRIBUTE_PURE
# define YY_ATTRIBUTE_PURE   YY_ATTRIBUTE ((__pure__))
#endif

#ifndef YY_ATTRIBUTE_UNUSED
# define YY_ATTRIBUTE_UNUSED YY_ATTRIBUTE ((__unused__))
#endif

/* Suppress unused-variable warnings by "using" E.  */
#if ! defined lint || defined __GNUC__
# define YYUSE(E) ((void) (E))
#else
# define YYUSE(E) /* empty */
#endif

#if defined __GNUC__ && ! defined __ICC && 407 <= __GNUC__ * 100 + __GNUC_MINOR__
/* Suppress an incorrect diagnostic about yylval being uninitialized.  */
# define YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN \
    _Pragma ("GCC diagnostic push") \
    _Pragma ("GCC diagnostic ignored \"-Wuninitialized\"")\
    _Pragma ("GCC diagnostic ignored \"-Wmaybe-uninitialized\"")
# define YY_IGNORE_MAYBE_UNINITIALIZED_END \
    _Pragma ("GCC diagnostic pop")
#else
# define YY_INITIAL_VALUE(Value) Value
#endif
#ifndef YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
# define YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
# define YY_IGNORE_MAYBE_UNINITIALIZED_END
#endif
#ifndef YY_INITIAL_VALUE
# define YY_INITIAL_VALUE(Value) /* Nothing. */
#endif

# ifndef YY_NULLPTR
#  if defined __cplusplus
#   if 201103L <= __cplusplus
#    define YY_NULLPTR nullptr
#   else
#    define YY_NULLPTR 0
#   endif
#  else
#   define YY_NULLPTR ((void*)0)
#  endif
# endif

/* Debug traces.  */
#ifndef YYDEBUG
# define YYDEBUG 0
#endif


namespace yy {
#line 148 "parser.hpp" // lalr1.cc:403

  /// A stack with random access from its top.
  template <typename T, typename S = std::vector<T> >
  class stack
  {
  public:
    // Hide our reversed order.
    typedef typename S::reverse_iterator iterator;
    typedef typename S::const_reverse_iterator const_iterator;
    typedef typename S::size_type size_type;

    stack (size_type n = 200)
      : seq_ (n)
    {}

    /// Random access.
    ///
    /// Index 0 returns the topmost element.
    T&
    operator[] (size_type i)
    {
      return seq_[size () - 1 - i];
    }

    /// Random access.
    ///
    /// Index 0 returns the topmost element.
    T&
    operator[] (int i)
    {
      return operator[] (size_type (i));
    }

    /// Random access.
    ///
    /// Index 0 returns the topmost element.
    const T&
    operator[] (size_type i) const
    {
      return seq_[size () - 1 - i];
    }

    /// Random access.
    ///
    /// Index 0 returns the topmost element.
    const T&
    operator[] (int i) const
    {
      return operator[] (size_type (i));
    }

    /// Steal the contents of \a t.
    ///
    /// Close to move-semantics.
    void
    push (YY_MOVE_REF (T) t)
    {
      seq_.push_back (T ());
      operator[](0).move (t);
    }

    void
    pop (int n = 1)
    {
      for (; 0 < n; --n)
        seq_.pop_back ();
    }

    void
    clear ()
    {
      seq_.clear ();
    }

    size_type
    size () const
    {
      return seq_.size ();
    }

    const_iterator
    begin () const
    {
      return seq_.rbegin ();
    }

    const_iterator
    end () const
    {
      return seq_.rend ();
    }

  private:
    stack (const stack&);
    stack& operator= (const stack&);
    /// The wrapped container.
    S seq_;
  };

  /// Present a slice of the top of a stack.
  template <typename T, typename S = stack<T> >
  class slice
  {
  public:
    slice (const S& stack, int range)
      : stack_ (stack)
      , range_ (range)
    {}

    const T&
    operator[] (int i) const
    {
      return stack_[range_ - i];
    }

  private:
    const S& stack_;
    int range_;
  };



  /// A char[S] buffer to store and retrieve objects.
  ///
  /// Sort of a variant, but does not keep track of the nature
  /// of the stored data, since that knowledge is available
  /// via the current state.
  template <size_t S>
  struct variant
  {
    /// Type of *this.
    typedef variant<S> self_type;

    /// Empty construction.
    variant ()
      : yybuffer_ ()
    {}

    /// Construct and fill.
    template <typename T>
    variant (YY_RVREF (T) t)
    {
      YYASSERT (sizeof (T) <= S);
      new (yyas_<T> ()) T (YY_MOVE (t));
    }

    /// Destruction, allowed only if empty.
    ~variant ()
    {}

    /// Instantiate an empty \a T in here.
    template <typename T>
    T&
    emplace ()
    {
      return *new (yyas_<T> ()) T ();
    }

# if defined __cplusplus && 201103L <= __cplusplus
    /// Instantiate a \a T in here from \a t.
    template <typename T, typename U>
    T&
    emplace (U&& u)
    {
      return *new (yyas_<T> ()) T (std::forward <U>(u));
    }
# else
    /// Instantiate a \a T in here from \a t.
    template <typename T>
    T&
    emplace (const T& t)
    {
      return *new (yyas_<T> ()) T (t);
    }
# endif

    /// Instantiate an empty \a T in here.
    /// Obsolete, use emplace.
    template <typename T>
    T&
    build ()
    {
      return emplace<T> ();
    }

    /// Instantiate a \a T in here from \a t.
    /// Obsolete, use emplace.
    template <typename T>
    T&
    build (const T& t)
    {
      return emplace<T> (t);
    }

    /// Accessor to a built \a T.
    template <typename T>
    T&
    as ()
    {
      return *yyas_<T> ();
    }

    /// Const accessor to a built \a T (for %printer).
    template <typename T>
    const T&
    as () const
    {
      return *yyas_<T> ();
    }

    /// Swap the content with \a other, of same type.
    ///
    /// Both variants must be built beforehand, because swapping the actual
    /// data requires reading it (with as()), and this is not possible on
    /// unconstructed variants: it would require some dynamic testing, which
    /// should not be the variant's responsibility.
    /// Swapping between built and (possibly) non-built is done with
    /// variant::move ().
    template <typename T>
    void
    swap (self_type& other)
    {
      std::swap (as<T> (), other.as<T> ());
    }

    /// Move the content of \a other to this.
    ///
    /// Destroys \a other.
    template <typename T>
    void
    move (self_type& other)
    {
# if defined __cplusplus && 201103L <= __cplusplus
      emplace<T> (std::move (other.as<T> ()));
# else
      emplace<T> ();
      swap<T> (other);
# endif
      other.destroy<T> ();
    }

# if defined __cplusplus && 201103L <= __cplusplus
    /// Move the content of \a other to this.
    template <typename T>
    void
    move (self_type&& other)
    {
      emplace<T> (std::move (other.as<T> ()));
      other.destroy<T> ();
    }
#endif

    /// Copy the content of \a other to this.
    template <typename T>
    void
    copy (const self_type& other)
    {
      emplace<T> (other.as<T> ());
    }

    /// Destroy the stored \a T.
    template <typename T>
    void
    destroy ()
    {
      as<T> ().~T ();
    }

  private:
    /// Prohibit blind copies.
    self_type& operator= (const self_type&);
    variant (const self_type&);

    /// Accessor to raw memory as \a T.
    template <typename T>
    T*
    yyas_ ()
    {
      void *yyp = yybuffer_.yyraw;
      return static_cast<T*> (yyp);
     }

    /// Const accessor to raw memory as \a T.
    template <typename T>
    const T*
    yyas_ () const
    {
      const void *yyp = yybuffer_.yyraw;
      return static_cast<const T*> (yyp);
     }

    union
    {
      /// Strongest alignment constraints.
      long double yyalign_me;
      /// A buffer large enough to store any of the semantic values.
      char yyraw[S];
    } yybuffer_;
  };


  /// A Bison parser.
  class parser
  {
  public:
#ifndef YYSTYPE
    /// An auxiliary type to compute the largest semantic type.
    union union_type
    {
      // "number"
      char dummy1[sizeof (int)];

      // "identifier"
      // "true"
      // "false"
      // "if"
      // "elif"
      // "else"
      // "while"
      // "return"
      // "state"
      // "entry"
      // "exit"
      // "on"
      // "moveto"
      // "lambda"
      // "defevent"
      // "int"
      // "bool"
      // "string"
      // "+"
      // ";"
      // "{"
      // "}"
      // "("
      // ")"
      // ","
      // "=<"
      // "=>"
      // "<"
      // ">"
      // "=="
      // "="
      char dummy2[sizeof (std::string)];
};

    /// Symbol semantic values.
    typedef variant<sizeof (union_type)> semantic_type;
#else
    typedef YYSTYPE semantic_type;
#endif

    /// Syntax errors thrown from user actions.
    struct syntax_error : std::runtime_error
    {
      syntax_error (const std::string& m);
    };

    /// Tokens.
    struct token
    {
      enum yytokentype
      {
        TOK_EOF = 0,
        TOK_IDENTIFIER = 258,
        TOK_NUMBER = 259,
        TOK_TRUE = 260,
        TOK_FALSE = 261,
        TOK_IF = 262,
        TOK_ELIF = 263,
        TOK_ELSE = 264,
        TOK_WHILE = 265,
        TOK_RETURN = 266,
        TOK_STATE = 267,
        TOK_ENTRY = 268,
        TOK_EXIT = 269,
        TOK_ON = 270,
        TOK_MOVETO = 271,
        TOK_LAMBDA = 272,
        TOK_DEFEVENT = 273,
        TOK_INT = 274,
        TOK_BOOL = 275,
        TOK_STRING = 276,
        TOK_PLUS = 277,
        TOK_SEMI = 278,
        TOK_LEFT_BRACE = 279,
        TOK_RIGHT_BRACE = 280,
        TOK_LEFT_PAREN = 281,
        TOK_RIGHT_PAREN = 282,
        TOK_COMMA = 283,
        TOK_LESS_EQUAL = 284,
        TOK_GREATER_EQUAL = 285,
        TOK_LESS = 286,
        TOK_GREATER = 287,
        TOK_EQUAL = 288,
        TOK_ASSIGN = 289
      };
    };

    /// (External) token type, as returned by yylex.
    typedef token::yytokentype token_type;

    /// Symbol type: an internal symbol number.
    typedef int symbol_number_type;

    /// The symbol type number to denote an empty symbol.
    enum { empty_symbol = -2 };

    /// Internal symbol number for tokens (subsumed by symbol_number_type).
    typedef unsigned char token_number_type;

    /// A complete symbol.
    ///
    /// Expects its Base type to provide access to the symbol type
    /// via type_get ().
    ///
    /// Provide access to semantic value.
    template <typename Base>
    struct basic_symbol : Base
    {
      /// Alias to Base.
      typedef Base super_type;

      /// Default constructor.
      basic_symbol ();

      /// Move or copy constructor.
      basic_symbol (YY_RVREF (basic_symbol) other);


      /// Constructor for valueless symbols, and symbols from each type.
      basic_symbol (typename Base::kind_type t);
      basic_symbol (typename Base::kind_type t, YY_RVREF (int) v);
      basic_symbol (typename Base::kind_type t, YY_RVREF (std::string) v);


      /// Destroy the symbol.
      ~basic_symbol ();

      /// Destroy contents, and record that is empty.
      void clear ();

      /// Whether empty.
      bool empty () const;

      /// Destructive move, \a s is emptied into this.
      void move (basic_symbol& s);

      /// The semantic value.
      semantic_type value;

    private:
#if defined __cplusplus && __cplusplus < 201103L
      /// Assignment operator.
      basic_symbol& operator= (const basic_symbol& other);
#endif
    };

    /// Type access provider for token (enum) based symbols.
    struct by_type
    {
      /// Default constructor.
      by_type ();

      /// Copy constructor.
      by_type (const by_type& other);

      /// The symbol type as needed by the constructor.
      typedef token_type kind_type;

      /// Constructor from (external) token numbers.
      by_type (kind_type t);

      /// Record that this symbol is empty.
      void clear ();

      /// Steal the symbol type from \a that.
      void move (by_type& that);

      /// The (internal) type number (corresponding to \a type).
      /// \a empty when empty.
      symbol_number_type type_get () const;

      /// The token.
      token_type token () const;

      /// The symbol type.
      /// \a empty_symbol when empty.
      /// An int, not token_number_type, to be able to store empty_symbol.
      int type;
    };

    /// "External" symbols: returned by the scanner.
    typedef basic_symbol<by_type> symbol_type;

    /// Build a parser object.
    parser (yy::Lexer& lexer_yyarg);
    virtual ~parser ();

    /// Parse.  An alias for parse ().
    /// \returns  0 iff parsing succeeded.
    int operator() ();

    /// Parse.
    /// \returns  0 iff parsing succeeded.
    virtual int parse ();

#if YYDEBUG
    /// The current debugging stream.
    std::ostream& debug_stream () const YY_ATTRIBUTE_PURE;
    /// Set the current debugging stream.
    void set_debug_stream (std::ostream &);

    /// Type for debugging levels.
    typedef int debug_level_type;
    /// The current debugging level.
    debug_level_type debug_level () const YY_ATTRIBUTE_PURE;
    /// Set the current debugging level.
    void set_debug_level (debug_level_type l);
#endif

    /// Report a syntax error.
    /// \param msg    a description of the syntax error.
    virtual void error (const std::string& msg);

    /// Report a syntax error.
    void error (const syntax_error& err);

    // Symbol constructors declarations.
    static
    symbol_type
    make_EOF ();

    static
    symbol_type
    make_IDENTIFIER (YY_COPY (std::string) v);

    static
    symbol_type
    make_NUMBER (YY_COPY (int) v);

    static
    symbol_type
    make_TRUE (YY_COPY (std::string) v);

    static
    symbol_type
    make_FALSE (YY_COPY (std::string) v);

    static
    symbol_type
    make_IF (YY_COPY (std::string) v);

    static
    symbol_type
    make_ELIF (YY_COPY (std::string) v);

    static
    symbol_type
    make_ELSE (YY_COPY (std::string) v);

    static
    symbol_type
    make_WHILE (YY_COPY (std::string) v);

    static
    symbol_type
    make_RETURN (YY_COPY (std::string) v);

    static
    symbol_type
    make_STATE (YY_COPY (std::string) v);

    static
    symbol_type
    make_ENTRY (YY_COPY (std::string) v);

    static
    symbol_type
    make_EXIT (YY_COPY (std::string) v);

    static
    symbol_type
    make_ON (YY_COPY (std::string) v);

    static
    symbol_type
    make_MOVETO (YY_COPY (std::string) v);

    static
    symbol_type
    make_LAMBDA (YY_COPY (std::string) v);

    static
    symbol_type
    make_DEFEVENT (YY_COPY (std::string) v);

    static
    symbol_type
    make_INT (YY_COPY (std::string) v);

    static
    symbol_type
    make_BOOL (YY_COPY (std::string) v);

    static
    symbol_type
    make_STRING (YY_COPY (std::string) v);

    static
    symbol_type
    make_PLUS (YY_COPY (std::string) v);

    static
    symbol_type
    make_SEMI (YY_COPY (std::string) v);

    static
    symbol_type
    make_LEFT_BRACE (YY_COPY (std::string) v);

    static
    symbol_type
    make_RIGHT_BRACE (YY_COPY (std::string) v);

    static
    symbol_type
    make_LEFT_PAREN (YY_COPY (std::string) v);

    static
    symbol_type
    make_RIGHT_PAREN (YY_COPY (std::string) v);

    static
    symbol_type
    make_COMMA (YY_COPY (std::string) v);

    static
    symbol_type
    make_LESS_EQUAL (YY_COPY (std::string) v);

    static
    symbol_type
    make_GREATER_EQUAL (YY_COPY (std::string) v);

    static
    symbol_type
    make_LESS (YY_COPY (std::string) v);

    static
    symbol_type
    make_GREATER (YY_COPY (std::string) v);

    static
    symbol_type
    make_EQUAL (YY_COPY (std::string) v);

    static
    symbol_type
    make_ASSIGN (YY_COPY (std::string) v);



  private:
    /// This class is not copyable.
    parser (const parser&);
    parser& operator= (const parser&);

    /// State numbers.
    typedef int state_type;

    /// Generate an error message.
    /// \param yystate   the state where the error occurred.
    /// \param yyla      the lookahead token.
    virtual std::string yysyntax_error_ (state_type yystate,
                                         const symbol_type& yyla) const;

    /// Compute post-reduction state.
    /// \param yystate   the current state
    /// \param yysym     the nonterminal to push on the stack
    state_type yy_lr_goto_state_ (state_type yystate, int yysym);

    /// Whether the given \c yypact_ value indicates a defaulted state.
    /// \param yyvalue   the value to check
    static bool yy_pact_value_is_default_ (int yyvalue);

    /// Whether the given \c yytable_ value indicates a syntax error.
    /// \param yyvalue   the value to check
    static bool yy_table_value_is_error_ (int yyvalue);

    static const signed char yypact_ninf_;
    static const signed char yytable_ninf_;

    /// Convert a scanner token number \a t to a symbol number.
    static token_number_type yytranslate_ (token_type t);

    // Tables.
  // YYPACT[STATE-NUM] -- Index in YYTABLE of the portion describing
  // STATE-NUM.
  static const signed char yypact_[];

  // YYDEFACT[STATE-NUM] -- Default reduction number in state STATE-NUM.
  // Performed when YYTABLE does not specify something else to do.  Zero
  // means the default is an error.
  static const unsigned char yydefact_[];

  // YYPGOTO[NTERM-NUM].
  static const signed char yypgoto_[];

  // YYDEFGOTO[NTERM-NUM].
  static const signed char yydefgoto_[];

  // YYTABLE[YYPACT[STATE-NUM]] -- What to do in state STATE-NUM.  If
  // positive, shift that token.  If negative, reduce the rule whose
  // number is the opposite.  If YYTABLE_NINF, syntax error.
  static const unsigned char yytable_[];

  static const unsigned char yycheck_[];

  // YYSTOS[STATE-NUM] -- The (internal number of the) accessing
  // symbol of state STATE-NUM.
  static const unsigned char yystos_[];

  // YYR1[YYN] -- Symbol number of symbol that rule YYN derives.
  static const unsigned char yyr1_[];

  // YYR2[YYN] -- Number of symbols on the right hand side of rule YYN.
  static const unsigned char yyr2_[];


#if YYDEBUG
    /// For a symbol, its name in clear.
    static const char* const yytname_[];

  // YYRLINE[YYN] -- Source line where rule number YYN was defined.
  static const unsigned char yyrline_[];
    /// Report on the debug stream that the rule \a r is going to be reduced.
    virtual void yy_reduce_print_ (int r);
    /// Print the state stack on the debug stream.
    virtual void yystack_print_ ();

    // Debugging.
    int yydebug_;
    std::ostream* yycdebug_;

    /// \brief Display a symbol type, value and location.
    /// \param yyo    The output stream.
    /// \param yysym  The symbol.
    template <typename Base>
    void yy_print_ (std::ostream& yyo, const basic_symbol<Base>& yysym) const;
#endif

    /// \brief Reclaim the memory associated to a symbol.
    /// \param yymsg     Why this token is reclaimed.
    ///                  If null, print nothing.
    /// \param yysym     The symbol.
    template <typename Base>
    void yy_destroy_ (const char* yymsg, basic_symbol<Base>& yysym) const;

  private:
    /// Type access provider for state based symbols.
    struct by_state
    {
      /// Default constructor.
      by_state ();

      /// The symbol type as needed by the constructor.
      typedef state_type kind_type;

      /// Constructor.
      by_state (kind_type s);

      /// Copy constructor.
      by_state (const by_state& other);

      /// Record that this symbol is empty.
      void clear ();

      /// Steal the symbol type from \a that.
      void move (by_state& that);

      /// The (internal) type number (corresponding to \a state).
      /// \a empty_symbol when empty.
      symbol_number_type type_get () const;

      /// The state number used to denote an empty symbol.
      enum { empty_state = -1 };

      /// The state.
      /// \a empty when empty.
      state_type state;
    };

    /// "Internal" symbol: element of the stack.
    struct stack_symbol_type : basic_symbol<by_state>
    {
      /// Superclass.
      typedef basic_symbol<by_state> super_type;
      /// Construct an empty symbol.
      stack_symbol_type ();
      /// Move or copy construction.
      stack_symbol_type (YY_RVREF (stack_symbol_type) that);
      /// Steal the contents from \a sym to build this.
      stack_symbol_type (state_type s, YY_MOVE_REF (symbol_type) sym);
#if defined __cplusplus && __cplusplus < 201103L
      /// Assignment, needed by push_back by some old implementations.
      /// Moves the contents of that.
      stack_symbol_type& operator= (stack_symbol_type& that);
#endif
    };

    /// Stack type.
    typedef stack<stack_symbol_type> stack_type;

    /// The stack.
    stack_type yystack_;

    /// Push a new state on the stack.
    /// \param m    a debug message to display
    ///             if null, no trace is output.
    /// \param sym  the symbol
    /// \warning the contents of \a s.value is stolen.
    void yypush_ (const char* m, YY_MOVE_REF (stack_symbol_type) sym);

    /// Push a new look ahead token on the state on the stack.
    /// \param m    a debug message to display
    ///             if null, no trace is output.
    /// \param s    the state
    /// \param sym  the symbol (for its value and location).
    /// \warning the contents of \a sym.value is stolen.
    void yypush_ (const char* m, state_type s, YY_MOVE_REF (symbol_type) sym);

    /// Pop \a n symbols from the stack.
    void yypop_ (int n = 1);

    /// Constants.
    enum
    {
      yyeof_ = 0,
      yylast_ = 5,     ///< Last index in yytable_.
      yynnts_ = 4,  ///< Number of nonterminal symbols.
      yyfinal_ = 7, ///< Termination state number.
      yyterror_ = 1,
      yyerrcode_ = 256,
      yyntokens_ = 35  ///< Number of tokens.
    };


    // User arguments.
    yy::Lexer& lexer;
  };

  // Symbol number corresponding to token number t.
  inline
  parser::token_number_type
  parser::yytranslate_ (token_type t)
  {
    static
    const token_number_type
    translate_table[] =
    {
     0,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     1,     2,     3,     4,
       5,     6,     7,     8,     9,    10,    11,    12,    13,    14,
      15,    16,    17,    18,    19,    20,    21,    22,    23,    24,
      25,    26,    27,    28,    29,    30,    31,    32,    33,    34
    };
    const unsigned user_token_number_max_ = 289;
    const token_number_type undef_token_ = 2;

    if (static_cast<int> (t) <= yyeof_)
      return yyeof_;
    else if (static_cast<unsigned> (t) <= user_token_number_max_)
      return translate_table[t];
    else
      return undef_token_;
  }

  inline
  parser::syntax_error::syntax_error (const std::string& m)
    : std::runtime_error (m)
  {}

  // basic_symbol.
  template <typename Base>
  parser::basic_symbol<Base>::basic_symbol ()
    : value ()
  {}

  template <typename Base>
  parser::basic_symbol<Base>::basic_symbol (YY_RVREF (basic_symbol) other)
    : Base (YY_MOVE (other))
    , value ()
  {
    switch (other.type_get ())
    {
      case 4: // "number"
        value.YY_MOVE_OR_COPY< int > (YY_MOVE (other.value));
        break;

      case 3: // "identifier"
      case 5: // "true"
      case 6: // "false"
      case 7: // "if"
      case 8: // "elif"
      case 9: // "else"
      case 10: // "while"
      case 11: // "return"
      case 12: // "state"
      case 13: // "entry"
      case 14: // "exit"
      case 15: // "on"
      case 16: // "moveto"
      case 17: // "lambda"
      case 18: // "defevent"
      case 19: // "int"
      case 20: // "bool"
      case 21: // "string"
      case 22: // "+"
      case 23: // ";"
      case 24: // "{"
      case 25: // "}"
      case 26: // "("
      case 27: // ")"
      case 28: // ","
      case 29: // "=<"
      case 30: // "=>"
      case 31: // "<"
      case 32: // ">"
      case 33: // "=="
      case 34: // "="
        value.YY_MOVE_OR_COPY< std::string > (YY_MOVE (other.value));
        break;

      default:
        break;
    }

  }


  // Implementation of basic_symbol constructor for each type.
  template <typename Base>
  parser::basic_symbol<Base>::basic_symbol (typename Base::kind_type t)
    : Base (t)
  {}

  template <typename Base>
  parser::basic_symbol<Base>::basic_symbol (typename Base::kind_type t, YY_RVREF (int) v)
    : Base (t)
    , value (YY_MOVE (v))
  {}

  template <typename Base>
  parser::basic_symbol<Base>::basic_symbol (typename Base::kind_type t, YY_RVREF (std::string) v)
    : Base (t)
    , value (YY_MOVE (v))
  {}



  template <typename Base>
  parser::basic_symbol<Base>::~basic_symbol ()
  {
    clear ();
  }

  template <typename Base>
  void
  parser::basic_symbol<Base>::clear ()
  {
    // User destructor.
    symbol_number_type yytype = this->type_get ();
    basic_symbol<Base>& yysym = *this;
    (void) yysym;
    switch (yytype)
    {
   default:
      break;
    }

    // Type destructor.
  switch (yytype)
    {
      case 4: // "number"
        value.template destroy< int > ();
        break;

      case 3: // "identifier"
      case 5: // "true"
      case 6: // "false"
      case 7: // "if"
      case 8: // "elif"
      case 9: // "else"
      case 10: // "while"
      case 11: // "return"
      case 12: // "state"
      case 13: // "entry"
      case 14: // "exit"
      case 15: // "on"
      case 16: // "moveto"
      case 17: // "lambda"
      case 18: // "defevent"
      case 19: // "int"
      case 20: // "bool"
      case 21: // "string"
      case 22: // "+"
      case 23: // ";"
      case 24: // "{"
      case 25: // "}"
      case 26: // "("
      case 27: // ")"
      case 28: // ","
      case 29: // "=<"
      case 30: // "=>"
      case 31: // "<"
      case 32: // ">"
      case 33: // "=="
      case 34: // "="
        value.template destroy< std::string > ();
        break;

      default:
        break;
    }

    Base::clear ();
  }

  template <typename Base>
  bool
  parser::basic_symbol<Base>::empty () const
  {
    return Base::type_get () == empty_symbol;
  }

  template <typename Base>
  void
  parser::basic_symbol<Base>::move (basic_symbol& s)
  {
    super_type::move (s);
    switch (this->type_get ())
    {
      case 4: // "number"
        value.move< int > (YY_MOVE (s.value));
        break;

      case 3: // "identifier"
      case 5: // "true"
      case 6: // "false"
      case 7: // "if"
      case 8: // "elif"
      case 9: // "else"
      case 10: // "while"
      case 11: // "return"
      case 12: // "state"
      case 13: // "entry"
      case 14: // "exit"
      case 15: // "on"
      case 16: // "moveto"
      case 17: // "lambda"
      case 18: // "defevent"
      case 19: // "int"
      case 20: // "bool"
      case 21: // "string"
      case 22: // "+"
      case 23: // ";"
      case 24: // "{"
      case 25: // "}"
      case 26: // "("
      case 27: // ")"
      case 28: // ","
      case 29: // "=<"
      case 30: // "=>"
      case 31: // "<"
      case 32: // ">"
      case 33: // "=="
      case 34: // "="
        value.move< std::string > (YY_MOVE (s.value));
        break;

      default:
        break;
    }

  }

  // by_type.
  inline
  parser::by_type::by_type ()
    : type (empty_symbol)
  {}

  inline
  parser::by_type::by_type (const by_type& other)
    : type (other.type)
  {}

  inline
  parser::by_type::by_type (token_type t)
    : type (yytranslate_ (t))
  {}

  inline
  void
  parser::by_type::clear ()
  {
    type = empty_symbol;
  }

  inline
  void
  parser::by_type::move (by_type& that)
  {
    type = that.type;
    that.clear ();
  }

  inline
  int
  parser::by_type::type_get () const
  {
    return type;
  }

  inline
  parser::token_type
  parser::by_type::token () const
  {
    // YYTOKNUM[NUM] -- (External) token number corresponding to the
    // (internal) symbol number NUM (which must be that of a token).  */
    static
    const unsigned short
    yytoken_number_[] =
    {
       0,   256,   257,   258,   259,   260,   261,   262,   263,   264,
     265,   266,   267,   268,   269,   270,   271,   272,   273,   274,
     275,   276,   277,   278,   279,   280,   281,   282,   283,   284,
     285,   286,   287,   288,   289
    };
    return static_cast<token_type> (yytoken_number_[type]);
  }

  // Implementation of make_symbol for each symbol type.
  inline
  parser::symbol_type
  parser::make_EOF ()
  {
    return symbol_type (token::TOK_EOF);
  }

  inline
  parser::symbol_type
  parser::make_IDENTIFIER (YY_COPY (std::string) v)
  {
    return symbol_type (token::TOK_IDENTIFIER, YY_MOVE (v));
  }

  inline
  parser::symbol_type
  parser::make_NUMBER (YY_COPY (int) v)
  {
    return symbol_type (token::TOK_NUMBER, YY_MOVE (v));
  }

  inline
  parser::symbol_type
  parser::make_TRUE (YY_COPY (std::string) v)
  {
    return symbol_type (token::TOK_TRUE, YY_MOVE (v));
  }

  inline
  parser::symbol_type
  parser::make_FALSE (YY_COPY (std::string) v)
  {
    return symbol_type (token::TOK_FALSE, YY_MOVE (v));
  }

  inline
  parser::symbol_type
  parser::make_IF (YY_COPY (std::string) v)
  {
    return symbol_type (token::TOK_IF, YY_MOVE (v));
  }

  inline
  parser::symbol_type
  parser::make_ELIF (YY_COPY (std::string) v)
  {
    return symbol_type (token::TOK_ELIF, YY_MOVE (v));
  }

  inline
  parser::symbol_type
  parser::make_ELSE (YY_COPY (std::string) v)
  {
    return symbol_type (token::TOK_ELSE, YY_MOVE (v));
  }

  inline
  parser::symbol_type
  parser::make_WHILE (YY_COPY (std::string) v)
  {
    return symbol_type (token::TOK_WHILE, YY_MOVE (v));
  }

  inline
  parser::symbol_type
  parser::make_RETURN (YY_COPY (std::string) v)
  {
    return symbol_type (token::TOK_RETURN, YY_MOVE (v));
  }

  inline
  parser::symbol_type
  parser::make_STATE (YY_COPY (std::string) v)
  {
    return symbol_type (token::TOK_STATE, YY_MOVE (v));
  }

  inline
  parser::symbol_type
  parser::make_ENTRY (YY_COPY (std::string) v)
  {
    return symbol_type (token::TOK_ENTRY, YY_MOVE (v));
  }

  inline
  parser::symbol_type
  parser::make_EXIT (YY_COPY (std::string) v)
  {
    return symbol_type (token::TOK_EXIT, YY_MOVE (v));
  }

  inline
  parser::symbol_type
  parser::make_ON (YY_COPY (std::string) v)
  {
    return symbol_type (token::TOK_ON, YY_MOVE (v));
  }

  inline
  parser::symbol_type
  parser::make_MOVETO (YY_COPY (std::string) v)
  {
    return symbol_type (token::TOK_MOVETO, YY_MOVE (v));
  }

  inline
  parser::symbol_type
  parser::make_LAMBDA (YY_COPY (std::string) v)
  {
    return symbol_type (token::TOK_LAMBDA, YY_MOVE (v));
  }

  inline
  parser::symbol_type
  parser::make_DEFEVENT (YY_COPY (std::string) v)
  {
    return symbol_type (token::TOK_DEFEVENT, YY_MOVE (v));
  }

  inline
  parser::symbol_type
  parser::make_INT (YY_COPY (std::string) v)
  {
    return symbol_type (token::TOK_INT, YY_MOVE (v));
  }

  inline
  parser::symbol_type
  parser::make_BOOL (YY_COPY (std::string) v)
  {
    return symbol_type (token::TOK_BOOL, YY_MOVE (v));
  }

  inline
  parser::symbol_type
  parser::make_STRING (YY_COPY (std::string) v)
  {
    return symbol_type (token::TOK_STRING, YY_MOVE (v));
  }

  inline
  parser::symbol_type
  parser::make_PLUS (YY_COPY (std::string) v)
  {
    return symbol_type (token::TOK_PLUS, YY_MOVE (v));
  }

  inline
  parser::symbol_type
  parser::make_SEMI (YY_COPY (std::string) v)
  {
    return symbol_type (token::TOK_SEMI, YY_MOVE (v));
  }

  inline
  parser::symbol_type
  parser::make_LEFT_BRACE (YY_COPY (std::string) v)
  {
    return symbol_type (token::TOK_LEFT_BRACE, YY_MOVE (v));
  }

  inline
  parser::symbol_type
  parser::make_RIGHT_BRACE (YY_COPY (std::string) v)
  {
    return symbol_type (token::TOK_RIGHT_BRACE, YY_MOVE (v));
  }

  inline
  parser::symbol_type
  parser::make_LEFT_PAREN (YY_COPY (std::string) v)
  {
    return symbol_type (token::TOK_LEFT_PAREN, YY_MOVE (v));
  }

  inline
  parser::symbol_type
  parser::make_RIGHT_PAREN (YY_COPY (std::string) v)
  {
    return symbol_type (token::TOK_RIGHT_PAREN, YY_MOVE (v));
  }

  inline
  parser::symbol_type
  parser::make_COMMA (YY_COPY (std::string) v)
  {
    return symbol_type (token::TOK_COMMA, YY_MOVE (v));
  }

  inline
  parser::symbol_type
  parser::make_LESS_EQUAL (YY_COPY (std::string) v)
  {
    return symbol_type (token::TOK_LESS_EQUAL, YY_MOVE (v));
  }

  inline
  parser::symbol_type
  parser::make_GREATER_EQUAL (YY_COPY (std::string) v)
  {
    return symbol_type (token::TOK_GREATER_EQUAL, YY_MOVE (v));
  }

  inline
  parser::symbol_type
  parser::make_LESS (YY_COPY (std::string) v)
  {
    return symbol_type (token::TOK_LESS, YY_MOVE (v));
  }

  inline
  parser::symbol_type
  parser::make_GREATER (YY_COPY (std::string) v)
  {
    return symbol_type (token::TOK_GREATER, YY_MOVE (v));
  }

  inline
  parser::symbol_type
  parser::make_EQUAL (YY_COPY (std::string) v)
  {
    return symbol_type (token::TOK_EQUAL, YY_MOVE (v));
  }

  inline
  parser::symbol_type
  parser::make_ASSIGN (YY_COPY (std::string) v)
  {
    return symbol_type (token::TOK_ASSIGN, YY_MOVE (v));
  }



} // yy
#line 1551 "parser.hpp" // lalr1.cc:403




#endif // !YY_YY_PARSER_HPP_INCLUDED
